### ISSUE TITLE
[bug]: Button startIcon and endIcon are too big

### ISSUE THREAD

**Issue by HichamELBSI** [strapi/design-system#1079]
### What version of strapi-design-system are you using?

Strapi Design System 1.7.7

### What's Wrong?

We have noticed that the size of the icons used for the `startIcon` and `endIcon` Button props has been changed. 

### To Reproduce

- Open the [Button with icons story](https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-button--icons)
- The icons seems to be rendered at a size of `1rem`

<img width="632" alt="Screenshot 2023-05-24 at 11 25 26" src="https://github.com/strapi/design-system/assets/7756284/6a759ce5-9953-4dfb-b36c-6c21ab8eeacc">

### Expected Behaviour

The expected size of the icons is  `0.75rem`

**Comment by gu-stav** [comment]
Fixed by https://github.com/strapi/design-system/pull/1089
