### ISSUE TITLE
CarouselSlide component is not working

### ISSUE THREAD

**Issue by smoothdvd** [strapi/design-system#1096]
### Required System information

- Node.js version: 18.16.0
- NPM version: pnpm 8.6.0
- Strapi version: 4.10.7
- Database: PostgreSQL 15
- Operating system: Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

CarouselSlide component is not working

### Steps to reproduce the behavior

1. Create a collection which has a field with media ( multiple images) type
2. add 50 images
3. See error

### Expected behavior

CarouselSlide component is working correctly ( size and layout)

### Screenshots

<img width="726" alt="Screenshot 2023-06-01 at 4 53 35 PM" src="https://github.com/strapi/strapi/assets/22420/562e652b-8a28-4ca8-bf9a-8b5ee89aff07">

**Comment by gu-stav** [comment]
Fix has been released in https://github.com/strapi/design-system/releases/tag/v1.7.10. It will be available with 4.11 next Wednesday in the CMS. 

Bump PR in the CMS: https://github.com/strapi/strapi/pull/16899

Thanks for reporting the issue.
