### ISSUE TITLE
[bug]: Dialog closes the Modal component

### ISSUE THREAD

**Issue by marco-villanueva** [strapi/design-system#1154]
### What version of strapi-design-system are you using?

npm: 8.3.0.
node: 16.17.0
Strapi: 4.11.2
Design-system: 1.8.0

### What's Wrong?

When I have a modal open, and this modal is going to open a confirmation window (Dialog component), any click on a button or not, closes the modal component. 

It seems to me that the DismissableLayer is causing conflicts between Modal, Dialog and PopOver.

### To Reproduce

1. Insert a modal
2. That the modal has a button or an actionable that raises a Dialog,
3. Click on the dialog body 
4. Observe how the modal that was behind closes. 

### Expected Behaviour

To be able to interact with the dialog without affecting the layers behind it such as the modal.

**Comment by joshuaellis** [comment]
solved in V2 of the design-system
