### ISSUE TITLE
[RFC]: Fix design system storybook

### ISSUE THREAD

**Issue by Boegie19** [strapi/design-system#1173]
### Context

Design system is not fully up to date + most examples miss big parts of the code needed to make them function

### Proposal

Update the design system storybook and make it fully uptodate and make all example runable

### Reasons

This should be done so that the design systems becomes easyer to use and would be better documented

**Comment by joshuaellis** [comment]
Thanks for this, I agree for sure there's an internal document i've been working on around improving it, but it's just trying to balance priorities 👍🏼

**Comment by H-Gomez** [comment]
Just commenting so I can following this. As someone who is building a plugin I am having to reference the source component props instead of the Storybook in order to get information on the design system.

**Comment by AdamSGit** [comment]
Same. I'm making a plugin and have an hard time to extract any useful information from the storybook. In the components section, anyone see how to display the source code of components exposed in playground ?

**Comment by yarkovaleksei** [comment]
The broken storybook was a disappointment. My first plugin was pieced together from google because of this))

**Comment by IslamAbdelhakiim** [comment]
Totally Agree, design system components variants are broken and to figure out the props from the source code is a creepy nightmare

**Comment by IslamAbdelhakiim** [comment]
I want to help, if anyone can tell me how to start fixing this, what should I learn to make it, I will do it ASAP

**Comment by joshuaellis** [comment]
relates to #625

**Comment by joshuaellis** [comment]
closing in favour of the aforementioned issue
