### ISSUE TITLE
[bug]: TypeError: Cannot read properties of undefined (reading 'withConfig') in nextjs 13

### ISSUE THREAD

**Issue by pamoman** [strapi/design-system#1174]
### What version of strapi-design-system are you using?

- Npm version = 8.19.3
- Node.js version = 16.19.0
- Strapi Design System version = 1.8.0
- Browser = Safari & Chrome
- Nextjs version = 13.4.7
- Using JavaScript not TypeScript

### What's Wrong?

I am unable to build a Nextjs production version of my application because of this error but everything works as expected in dev mode even though the error is logged there too. The error seems to originate from the Box component only.

Dev error
![image-1](https://github.com/strapi/design-system/assets/60609422/6dd24908-9528-4b3e-8ddd-6980a50bd872)

Production error
![image-2](https://github.com/strapi/design-system/assets/60609422/e3e43ba7-679d-4365-9bc9-61b7dfe3a6f9)

### To Reproduce

Run Nextjs in dev mode or perform a production build. Building can never complete because of this error.

### Expected Behaviour

No error and building can complete successfully.

**Comment by joshuaellis** [comment]
What version of `styled-components` are you using?

**Comment by pamoman** [comment]
> 

v5.3.11

**Comment by joshuaellis** [comment]
Are you using a monorepo setup? It looks like nextjs can't find the dependency, imho your problem is with nextjs, not the DS

**Comment by pamoman** [comment]
No monorepo just a single next.js project. Step 1 and 3 in the guide are complete, not step 2 though.

**Comment by pamoman** [comment]
Now step 2 is complete. I needed to install v6+ of styled-components as the guide says so now am using v6.0.2.  When removing the node_modules folder and lock file I now get a conflict error when installing the package.json for a clean start. Also in dev mode I get a new error and the old error remains logged too.

<img width="952" alt="Screenshot 2023-07-03 at 11 21 26" src="https://github.com/strapi/design-system/assets/60609422/6f0a6230-4c90-4917-b2f3-de418a8e9f91">

Here is what I return from my layout file:

![Screenshot 2023-07-03 at 11 27 30](https://github.com/strapi/design-system/assets/60609422/10ce27c8-7727-43b2-9423-51abaddaa175)

**Comment by joshuaellis** [comment]
It's probably because styled-components v5 is not compatible with the `RSC/appDir` format of nextjs 13, you'd need to open this issue with nextjs or styled-components.

We'll be upgrading to styled-components v6 at some point this year now it's been released.

**Comment by pamoman** [comment]
Ok, so your saying Strapi Design System is not currently compatible with next.js 13?

**Comment by joshuaellis** [comment]
No, im saying the design system is using styled-components 5 which from your issue seems to have issues with nextjs RSCs.

**Comment by pamoman** [comment]
Ok, I will check out the next.js forums to see if there is a workaround. Otherwise I will have to downgrade to next.js v12.

**Comment by pamoman** [comment]
Thanks for the fast help anyway!

**Comment by pamoman** [comment]
What versions of next.js and styled-components do you recommend I use for maximum compatibility with the design system?
