### ISSUE TITLE
[feat]: MultiSelect and MultiSelectNested component's value prop supports number[]

### ISSUE THREAD

**Issue by smoothdvd** [strapi/design-system#1176]
### A clear and concise description of what the feature is

MultiSelect and MultiSelectNested component's value prop supports number[]

### Why should this feature be included?

value prop sometimes will be like [1, 2, 3]

### Please provide an example for how this would work

```
<MultiSelect value={[1, 2, 3]} ...{restProps}>...</MultiSelect>
```

**Comment by joshuaellis** [comment]
Our select is based off – https://www.radix-ui.com/docs/primitives/components/select#root and I don't think we want to support numbers as values as the `Option`'s values are also strings, i think this would just make the API more complicated than it needs to be to be honest, e.g. your code could be:

```
<MultiSelect value={[1, 2, 3].map(v => v.toString())} ...{restProps}>...</MultiSelect>
```
