### ISSUE TITLE
[bug]: v2 components are not exported and can't be used in TypeScript

### ISSUE THREAD

**Issue by pigletz-dev** [strapi/design-system#1178]
### What version of strapi-design-system are you using?

- Node.js version: 18.16.1
- deisgn-system: 1.8.1
- TypeScript

### What's Wrong?

The Storybook suggests v2 components to be used like:

```typescript
import { SimpleMenu, MenuItem } from '@strapi/design-system/v2';
```

However since v2 are not exported I got error:
`Cannot find module '@strapi/design-system/v2' or its corresponding type declarations.`

In JavaScript this module can be imported. 

### To Reproduce

try importing in typescript project: 

```typescript
import { SimpleMenu, MenuItem } from '@strapi/design-system/v2';
```

### Expected Behaviour

v2 components must be importable (exported) as the documentation suggests.

**Comment by joshuaellis** [comment]
We don't actually publish any of our types yet because it's a breaking change and we need to manage a CMS dependency on no breaking changes.... hopefully soon though 🤞🏼

There's an older issue to keep an eye on.

**Comment by pigletz-dev** [comment]
> a breaking change and we need to manage a CMS dependency on no breaking changes.... hopefully soon though 🤞🏼

Thanks for the answer. Just wondered if I can use those since it is documented that I can and I actually can in javascript projects just not in ts. Hopefully soon then :)

**Comment by obax** [comment]
Is there any chance that these types could be exported by a `@types/` package? That way the current package does not move at all
