### ISSUE TITLE
[bug]: Combobox returning NULL if no option is available

### ISSUE THREAD

**Issue by noobCode-69** [strapi/design-system#1185]
### What version of strapi-design-system are you using?

- Npm version : Not applicable
- Node version : Not applicable
- Browser : Every browser

### What's Wrong?

If you don't have any options for Combobox there is nothing in the screen to show  that.

### To Reproduce

- Go to the Combobox storybook file 
- Remove Combobox options 
- Go to localhost 
- open Combobox story 

### Expected Behaviour

I expect a placeholder message that reads "Nothing available"

**Comment by noobCode-69** [comment]
I think the same bug , is causing issue "CM: Relations no longer display "No relations available" when target CT is empty #17231" in the strapi repo

**Comment by madhurisandbhor** [comment]
duplicate issue https://github.com/strapi/design-system/issues/1626, so closing this one
