### ISSUE TITLE
[bug]: DateTimePicker changes date automatically (only for some timezones?)

### ISSUE THREAD

**Issue by alimpens** [strapi/design-system#1223]
### What version of strapi-design-system are you using?

- Strapi Design System version: 1.8.1

### What's Wrong?

When selecting a date in the DateTimePicker, that date minus one day is shown in the UI. If you click on the corresponding label, another day is subtracted from the date.

Possibly related to timezones and [this PR for the DatePicker](https://github.com/strapi/design-system/pull/1172/files#). I'm in the GMT+2 timezone. 

### To Reproduce

- Go to [the DateTimePicker in Storybook](https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-datetimepicker--base)
- Select today's date
- See that yesterday's date is show in the UI
- Click on the 'Publish at' label
- See that another day is subtracted in the UI

Possibly related to the users timezone. I'm in GMT+2

### Expected Behaviour

I expect the date I pick to be shown in the UI, and for it not to change when I click the label.

**Comment by smoothdvd** [comment]
Same to me, I'm GMT+8

**Comment by Martijn-Schoenmaker-Webbio** [comment]
I opened the same issue in the Strapi repo --> https://github.com/strapi/strapi/issues/17538

**Comment by marob** [comment]
There's a fix pending review: https://github.com/strapi/design-system/pull/1241
You can see the fix in action [here](https://design-system-git-fork-marob-fix-1223-datetimep-5c2733-strapijs.vercel.app/?path=/story/design-system-components-datetimepicker--base).
