### ISSUE TITLE
[bug]: @strapi dependencies are not updated in the docs directory

### ISSUE THREAD

**Issue by gu-stav** [strapi/design-system#1260]
### What version of strapi-design-system are you using?

- Design system version: 1.8.1

### What's Wrong?

Dependencies are not updated in the docs directory: https://github.com/strapi/design-system/blob/de08397405ad4173ac752cfa8a6cc1d71e1145a8/docs/package.json#L13-L15

### To Reproduce

see above

### Expected Behaviour

I expect the dependency versions to be bumped along with the other packages.

**Comment by joshuaellis** [comment]
caused by the wishes of #855 in a way, i.e. its not part of the monorepo so lerna doesn't care.
