### ISSUE TITLE
[feat]: add views/interfaces

### ISSUE THREAD

**Issue by ComfortablyCoding** [strapi/design-system#1269]
### A clear and concise description of what the feature is

It would be nice if common views/interfaces and complex components that are used/seen throughout the Strapi admin where exposed via the strapi design system.

Some examples are
- Table View (i.e. Content Type View)
- Settings View
- Form View
- Modal View

### Why should this feature be included?

As a plugin developer when creating an admin interface we consistently find ourselves re-creating interfaces that exist in strapi but are not exposed via the design system. This leads to a lot of duplicated logic that we need to re-create so our interfaces are inline with Strapis.

It will also reduce the amount of custom logic and spread out components that are baked into the admin codebase instead of living in the design system. 

Any component or view/interface seen in Strapi should be exposed or easily created via the design system to provide a unified interface. I believe adding common views/interfaces is the first step towards that.

### Please provide an example for how this would work

Components with Interface or View suffix will be exposed from the design system that the Strapi admin and plugin developers can then consume. 
```js
// import Table View
import { TableView } from '@strapi/design-system';
```

**Comment by joshuaellis** [comment]
While I think the use case is interesting, I don't think this will be done in the `design-system`, this project is agnostic to our others i.e. we use this on the `cloud` and `cms` and we want to actually make this project even more agnostic, but feedback on pieces to be exported from the cms are very useful – currently we have a `helper-plugin` (not well documented) that exports a lot of pieces at the moment, in V5 we'll be shuffling some stuff round and hope to export things from `@strapi/admin`, I'd actually re-write this request in Canny so we have some visibility on it going forward :)
