### ISSUE TITLE
[bug]: relation field catch every drag and drop event

### ISSUE THREAD

**Issue by AlcaYezzz** [strapi/design-system#1298]
### What version of strapi-design-system are you using?

yarn version: 1.22.19
npm version: 18.13.0
strapi version: 4.11.7
strapi design system version: 1.8.0

### What's Wrong?

The relation field catch every drag and drop event once a relation is selected, this break the drag n drop of other fields and prevent us from building complex custom field to improve our user experience with Strapi.

   

### To Reproduce

Create a content type with 2 fields:
  - 1 text (long text)
  - 1 relation to another entity (the second entity content doesn't matter)
 
As you can see in the below video, as long as no relation is provided, the drag'n drop functionality of the text area is working. As soon as we set a relation, the drag'n drop functionality of the text area fail
  
[Screencast from 18-08-2023 09:22:03.webm](https://github.com/strapi/design-system/assets/125576333/8d84edd3-d6d9-4c28-953b-7691636722c7)

### Expected Behaviour

The drag'n drop event of a field shouldn't be impacted by those of other fields.

**Comment by joshuaellis** [comment]
Sorry there was some confusion, this does belong in the other repo :)
