### ISSUE TITLE
[bug]: HeaderLayout doesn't recalculate height

### ISSUE THREAD

**Issue by gu-stav** [strapi/design-system#1318]
### What version of strapi-design-system are you using?

- Strapi Design System: 1.9.0

### What's Wrong?

`Headerlayout` calculates its height, because the component becomes sticky. The height is only calculated on initial render.

This becomes a problem when e.g. the content of the subtitle is dynamically fetched (review workflows) and rendered, because they height of the element increases, but is not taken into account.

### To Reproduce

1. Render `Headerlayout` and render content of the subtitle prop programmatically with a delay.

### Expected Behaviour

The component should respond to its content. It is probably not necessary to calculate the height dynamically.

**Comment by joshuaellis** [comment]
This component has been moved to the strapi admin panel for v5 & does not exist in v2 of the design-system, therefore, we will close this issue.

**Comment by khuongtp** [comment]
So it's not exported anymore? Is there any way to use that component, please?
