### ISSUE TITLE
[bug]: Dialog overflows unscrollable

### ISSUE THREAD

**Issue by Martin-Eckleben** [strapi/design-system#1328]
### What version of strapi-design-system are you using?

NPM 8.1.2
Node v16.13.2 
Strapi v4.9.0
Browser Chrome 116.0.5845.141

### What's Wrong?

Dialog does not scroll when the content overflows.
Instead it runs off the screen - never to be reached and read
(and Dialog Footer Buttons never to be pressed).

Tried to make it scrollable by overwriting CSS but does not seem simple with react portal etc.

![image](https://github.com/strapi/design-system/assets/1571683/9a7f3627-95b2-4f59-9b74-e8bd96d77bea)

### To Reproduce

Fill a Dialog with more content than vertical space on the screen.

### Expected Behaviour

Scroll probably.

**Comment by joshuaellis** [comment]
should be resolved by [#1727](https://github.com/strapi/design-system/issues/1727)
