### ISSUE TITLE
[bug]: Disabled focus state of Select and Combobox is inconsistent

### ISSUE THREAD

**Issue by gu-stav** [strapi/design-system#1330]
### What version of strapi-design-system are you using?

- Design-System: 1.10.0

### What's Wrong?

The focus state of a disabled `Select` and `Combobox` is inconsistent. While `Select` does not display the focus outline (which imo is the proper behavior) the `Combobox` does:

https://github.com/strapi/design-system/assets/2244375/74194dc8-08c4-455d-9891-2c693ca91580

### To Reproduce

1. Use `Select` and `Combobox` next to each other
2. Add `disabled=true` to both
3. Focus both fields

### Expected Behaviour

I expect `Combobox` to not receive any events nor display a visible focus state. It could also be discussed which cursor to display in this case, because it is inconsistent too.

**Comment by Parathantl** [comment]
Hi @gu-stav,
I am new to the Strapi contribution. Would it possible for me to take this? If you could give me guidance It would be grateful
