### ISSUE TITLE
[feat]: Wish the SubNav component can be collapsed

### ISSUE THREAD

**Issue by zhangchuachua** [strapi/design-system#1349]
### A clear and concise description of what the feature is

The SubNav component can be **collapsed** or the width can be adjusted.

### Why should this feature be included?

strapi version: 4.12.4

when I upgrade strapi to v4, the width of editor was too small for me;

the picture below is an example:

![image](https://github.com/strapi/design-system/assets/57211927/b5d7f7e2-385d-4f03-8724-45ef6d12ec0d)

so, I wish the SubNav component can be **collapsed** or the width can be adjusted.

### Please provide an example for how this would work

I don't think it's necessary to provide a minimal repro, just adjust the browser's width to 1280px

**Comment by joshuaellis** [comment]
I think this should actually be a feature request on [Canny](https://strapi.canny.io/) not the design-system, because it's a product decision to change this
