### ISSUE TITLE
When developing a strapi plugin, is there a reason why I must use the strapi design-system?

### ISSUE THREAD

**Issue by kincjf** [strapi/design-system#1414]
### Context

**Hello, I have been using strapi for 2 years, but I am a beginner in strapi plugin development.**

I am asking this question because I am considering various scenarios for strapi-based plugin development. We look forward to hearing from someone with experience.

- When developing strapi plugin, is it absolutely necessary to use strapi design-system? Is there a reason why you must use the strapi design-system?

- When developing strapi plugin, can I use a different react UI framework other than strapi design-system?

- We are planning to move the previously developed functions using React Material-UI into the strapi plugin. Is this still okay?

- When developing strapi plugin, is it okay to use other react UI framework and strapi design-system together?

- When developing a site with a standalone react dashboard, is it okay to use strapi design-system (together)?
Our plan is to develop and use the strapi plugin, but if the functionality becomes too extensive, we may migrate to a standalone dashboard.

### Proposal

**Hello, I have been using strapi for 2 years, but I am a beginner in strapi plugin development.**

In addition to design unity with strapi, I am curious whether the strapi design-system has other functional advantages, such as ease of functional integration with strapi.

**Comment by joshuaellis** [comment]
Thanks for asking! It's a great question – if you want your plugin to be listed on our marketplace then yes, you must use the design-system for the UI.

If you're not interested in that then using the design system is not required to develop a plugin 🙂 however, having said that there's a huge benefit to using the design system, namely UI consistency across the product your users are working with.
