### ISSUE TITLE
[bug]: When there is no scroll bar on the page, the floating position of Tooltip will shift

### ISSUE THREAD

**Issue by BlueBaidu** [strapi/design-system#1420]
### What version of strapi-design-system are you using?

DS:v1.12.1
Operating system: Windows
Browser: Chromium Version 118.0.5993.71 (official version) (64 bit), Microsoft Edge Version 114.0.1823.37 (official version) (64 bit)

### What's Wrong?

When there is no scroll bar on the page, the first time the hover is on the icon, the position of the Tooltip shifts and does not appear directly above the icon. After hovering again, the Tooltip position returns to normal.
![image](https://github.com/strapi/design-system/assets/101248999/d4394574-a6d4-4cd6-9ff3-763398d738c3)
![image](https://github.com/strapi/design-system/assets/101248999/f13ad0bf-cab0-4cf5-a661-3643a005a9f9)

### To Reproduce

This behaviour is also visible on the demo documentation page:
https://api-0khig.strapidemo.com/admin/plugins/content-type-builder/content-types/api::place.place

### Expected Behaviour

The suspension position of Tooltip exhibits consistency between the first hover and subsequent hovers

**Comment by joshuaellis** [comment]
solved by #1722
