### ISSUE TITLE
[bug]: error TS7016: Could not find a declaration file for module '@strapi/design-system'.

### ISSUE THREAD

**Issue by rktyt** [strapi/design-system#1466]
### What version of strapi-design-system are you using?

Npm version: 9
Node.js version: 18
Strapi Design System version: 1.13.0 | 1.13.1
Strapi version: 4.15.4

### What's Wrong?

error TS7016: Could not find a declaration file for module '@strapi/design-system'.

----

Does it not support typescript yet?

### To Reproduce

package.json:
```json
{
  "devDependencies": {
    "@strapi/typescript-utils": "4.15.4",
    "typescript": "5.2.2"
  },
  "dependencies": {
    "@strapi/design-system": "1.13.0"
  }
}
```

tsconfig.json:
```json
{
  "extends": "@strapi/typescript-utils/tsconfigs/admin"
}
```

index.tsx:
```typescript
import { Layout } from '@strapi/design-system';
```

After creating the above files, run the following command
```
npm install && npx tsc --noEmit
```

### Expected Behaviour

no errors occur

**Comment by joshuaellis** [comment]
Types won't be published till V2

**Comment by Martijn-Schoenmaker-Webbio** [comment]
Why close this issue? Plugins using typescript now don't work anymore. Building the plugin works and doesn't produce any error. Building Strapi with the plugins will produce the errors statet above.
