### ISSUE TITLE
[bug]: Link v2 has no hover color/effect

### ISSUE THREAD

**Issue by t-fritsch** [strapi/design-system#1525]
### What version of strapi-design-system are you using?

strapi 4.15.5

### What's Wrong?

Link v2 doesn't show the hover color on rollover

### To Reproduce

go to https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-v2-link--docs
rollover any link, style doesn't get updated on hover

### Expected Behaviour

The hover color defined here should be shown on rollover :
https://github.com/strapi/design-system/blob/85c0cbbe468155fd9d33817aa40feac8bc633889/packages/strapi-design-system/src/v2/Link/Link.tsx#L25-L27

It doesn't show up because it is overridden by the `<Typography>` component inside :
https://github.com/strapi/design-system/blob/85c0cbbe468155fd9d33817aa40feac8bc633889/packages/strapi-design-system/src/v2/Link/Link.tsx#L50

In Link V1, the hover effect works because the Typography component uses the [`currentColor` CSS value](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword) : 
https://github.com/strapi/design-system/blob/85c0cbbe468155fd9d33817aa40feac8bc633889/packages/strapi-design-system/src/Link/Link.tsx#L27-L30

(Note anyway that putting a Typography component with no prop passing on it makes it impossible to fix this kind of bug on our side, and prevents also customizing the text, for adding ellipsis on it for example. I pray every day that styled component in strapi gets dropped in favor of real css 😂 ...)

**Comment by joshuaellis** [comment]
PRs always welcome!

**Comment by t-fritsch** [comment]
Well I'm glad that taking the time to make a proper issue is so much appreciated... 🤦‍♂️ 

We already passed a lot of time struggling with the design system without any real documentation (not mentioning the fight with the rigidity of the whole strapi's frontend) but that's another issue. 
If we had the time to dig even more in the code of the design system we'd have already done a PR thanks, but please understand that if I submit an issue instead of a PR this is for a reason. 
If you don't value it, feel free to close it.

**Comment by joshuaellis** [comment]
I think we've had the discussion on the documentation & what you describe as the rigidity of strapi as well on discord, I can see you're frustrated & you've communicated this a few times. Unfortunately if you're not willing to give time for these issues to be solved then there's not much more I can do.

I of course appreciate the effort you've gone to to create a bug report, I just as with a few issues that I think are potentially easily solvable is remind people that PRs are welcome 😊 no one was commenting on your ability to decide whether to open an issue or a PR.

**Comment by t-fritsch** [comment]
I already gave time for this issues to

**Comment by t-fritsch** [comment]
@joshuaellis  I'm not "**_not willing to give time for these issues_**"... this is quite insulting since I just "**_gave time_**" (and a lot) for submitting issues as detailed as possible, pointing to the probable cause, to help people at strapi with better knowledge of the system to do the fix. Not mentioning the time passed on discord trying to help ppl.

I understand you'd want **_even more_** help, but by only replying "_PRs are welcome!_" after an issue that took more than half an hour to document/redact I'm sure you can understand how disrespectful it sounds when you "give time" to help strapi gets better instead of leaving for another product.

edit: deleted previous comment submitted too quickly by misclick

**Comment by joshuaellis** [comment]
Hey, no you've misunderstood – when I was referring to give time to these issues, i was talking about your repetitive vocal frustration about front-end customisation & design-system documentation not this issue specifically.

**Comment by t-fritsch** [comment]
Pardon me but whether you speak of this issue or generally, saying that I'm not willing to "give time" to those subjects (FE customization, etc) is still not true : 
As you said yourself we already had "time" to discuss those topics in discord/github (and even if you made this personal from the very beginning, I want to remind you that it definitely wasn't, plus I'm not the only one raise those problems in strapi direction). I even accepted to "give time" to an interview with a strapi's PM to further discuss use cases and pain points met in our work with strapi UI. 
Anyway I'm not a strapi team member, the time I "give" is free, saying that if I cannot give "more" then you "don't know what more you can do" is really disappointing from a user perspective.

Anyway if you still have concerns about my personal implication in strapi and the time I give or not, I suggest that you could maybe DM/mention me on discord instead of making reproaches in this issue comment section.
