### ISSUE TITLE
[bug]: Change the NavLink component to support other values for the badgeContent attribute other than strings

### ISSUE THREAD

**Issue by simotae14** [strapi/design-system#1590]
### What version of strapi-design-system are you using?

- Npm version: 9.6.7
- Node.js version: 20.3.1
- Strapi Design System version: 1.14.0
Browser: Chrome

### What's Wrong?

When you want to add for example an icon in the right side of a NavLink you can't do it because the badgeContent accept only strings as values.
For example in this case we want to accept the LockIcon as content for the badgeContent attribute
![same as releases](https://github.com/strapi/design-system/assets/2589748/e8661fb1-2e34-45dd-9347-cb1068e74cb0)
In addiction it will be helpful to create a property to change the badgeContent wrapper background color (today always set)

### To Reproduce

Go to the CMS without license and take a look at the Left menu in the side bar, you can see the Release Content Link with a lock icon on the right.
It uses a NavLink component passing the icon as badgeContent, we want to accept this type of content without type errors.
And it will be useful also to pass a badground color or a variant for the badgeContent color

### Expected Behaviour

In the future we need to have the possibility to pass Icons for example as badgeContent and to set the background color of the badge content wrapper

**Comment by joshuaellis** [comment]
The MainNav components were moved to the CMS monorepo for V5 and won't be part of the V2 design-system, therefore we will not work on this.
