### ISSUE TITLE
[bug]: Popover does not close with the same button

### ISSUE THREAD

**Issue by MikhailTyuftyaev** [strapi/design-system#1700]
### What version of strapi-design-system are you using?

Npm version: 8.15.1
Node.js version: 20.11.1
Strapi Design System version: 1.14.1
Browser: Chrome

### What's Wrong?

When you open a pop-up window with a button, it does not close on the second click (as it should be). I think this is due to the fact that both events are triggered: OnClick on the button, and onDismiss on the Popover. They change each other's states. 

As you can see in this video, this bug is in [Storybook Strapi](https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-popover--docs). Also, when creating my plugin, I got the same error.

https://github.com/strapi/design-system/assets/53301242/0ba21fb4-a795-449c-8222-89d5da783b08

### To Reproduce

This bug you can find the error in [Storybook Strapi](https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-popover--docs).

### Expected Behaviour

Each time the button is clicked, the Popover must either open or close.

**Comment by joshuaellis** [comment]
should be solved by a843b4cd
