### ISSUE TITLE
[bug]: BoxProps makes CSSProperties mandatory.

### ISSUE THREAD

**Issue by alexleach** [strapi/design-system#1704]
### What version of strapi-design-system are you using?

npm v10.5.0
node v20.12.1
Strapi design-system from git: releases/2.0.0

### What's Wrong?

I'm using a strapi plugin written in typescript, [strapi-plugin-generate-data](https://github.com/MaksZhukov/strapi-plugin-generate-data), which fails to compile with the v2 beta releases. Among other things, it complains about various objects missing required CSS Properties, for example:

```
admin/src/components/Generate/Generate.tsx(274,4): error TS2740: Type '{ children: string; startIcon: Element; onClick: () => Promise<void>; }' is missing the following properties from type 'ButtonProps': cursor, display, overflow, pointerEvents, and 7 more.
```

These properties are defined in [`Box.tsx`](https://github.com/strapi/design-system/blob/releases/2.0.0/packages/strapi-design-system/src/Box/Box.tsx):

```
export type BoxProps<TElement extends keyof JSX.IntrinsicElements = 'div'> = React.ComponentPropsWithoutRef<TElement> &
  Pick<
    CSSProperties,
    | 'pointerEvents'
    | 'display'
    | 'position'
    | 'zIndex'
    | 'overflow'
    | 'cursor'
    | 'transition'
    | 'transform'
    | 'animation'
    | 'textAlign'
    | 'textTransform'
  > & {
[...]
}
```

### To Reproduce

```bash
$ git clone https://github.com/MaksZhukov/strapi-plugin-generate-data.git --depth 1
$ cd strapi-plugin-generate-data
$ npm install -g npm-check-updates
$ npm-check-updates @strapi/design-system @strapi/icons -u -t '@[beta]'

# Manually update the Node engine in package.json to "node": ">=14.19.1 <=20.x.x",

$ yarn install
```

There are a load of other issues that require updates to `strapi-plugin-generate-data`. I've created a [PR](https://github.com/MaksZhukov/strapi-plugin-generate-data/pull/56) for those already, to get it ready for strapi-design-system v2 and strapi-v5.

But the error I mention above I bellieve requires an update to this package.

### Expected Behaviour

I don't believe the CSS Properties defined on `BoxProps` should be made mandatory, and instead should be made optional.

I've made what I consider a fix for this, and will create a PR shortly:

```diff
diff --git a/packages/strapi-design-system/src/Box/Box.tsx b/packages/strapi-design-system/src/Box/Box.tsx
index b6611d72..d9bb769c 100644
--- a/packages/strapi-design-system/src/Box/Box.tsx
+++ b/packages/strapi-design-system/src/Box/Box.tsx
@@ -7,19 +7,21 @@ import { extractStyleFromTheme } from '../helpers/theme';
 import { DefaultThemeOrCSSProp } from '../types';
 
 export type BoxProps<TElement extends keyof JSX.IntrinsicElements = 'div'> = React.ComponentPropsWithoutRef<TElement> &
-  Pick<
-    CSSProperties,
-    | 'pointerEvents'
-    | 'display'
-    | 'position'
-    | 'zIndex'
-    | 'overflow'
-    | 'cursor'
-    | 'transition'
-    | 'transform'
-    | 'animation'
-    | 'textAlign'
-    | 'textTransform'
+  Partial<
+    Pick<
+      CSSProperties,
+      | 'pointerEvents'
+      | 'display'
+      | 'position'
+      | 'zIndex'
+      | 'overflow'
+      | 'cursor'
+      | 'transition'
+      | 'transform'
+      | 'animation'
+      | 'textAlign'
+      | 'textTransform'
+    >
   > & {
     /**
      * JavaScript hover handler
```

**Comment by joshuaellis** [comment]
I think the issue comes from the fact the library in question has installed `@strapi/design-system` but none of it's peer deps – `react/react-dom/styled-components/react-router-dom` and it's associated type packages, which means `Box`'s props can't be correctly inferred, CSSProperties comes from `styled-components` and all are optional by default. Have you tried doing this?

**Comment by alexleach** [comment]
You're right that I have various warnings about `unmet peer dependencies` and `incorrect peer dependency' issued by `yarn`. So many in fact, that it's really hard knowing which packages are causing the warnings to be generated, and which packages should be providing those peer dependencies. Should the peer dependencies you mentioned come from [@strapi/strapi](https://github.com/strapi/strapi/)?

This seems to be quite a mammoth task setting up the [monorepo template](https://github.com/SGFGOV/medusa-strapi-repo) I'm using with Strapi-v5 beta and Strapi/design-system v2 beta. It's a work in progress that I'm trying to juggle with other jobs, so apologies for my slow response...
