### ISSUE TITLE
[bug]: 2.0.0-beta.2 codemirror error Unrecognized extension value in extension set 

### ISSUE THREAD

**Issue by markkaylor** [strapi/design-system#1706]
### What version of strapi-design-system are you using?

2.0.0-beta.2

### What's Wrong?

Use of the JSON input throws the following error:

<img width="697" alt="Screenshot 2024-04-26 at 12 03 36" src="https://github.com/strapi/design-system/assets/26598053/46c63039-e746-489e-8bd1-9645a45ea144">

### To Reproduce

On [Strapi v5/main](https://github.com/strapi/strapi/tree/v5/main) go to any content-type in the content manager that is using the JSON input. You will see the error. 

### Expected Behaviour

No error when using the JSON input

**Comment by joshuaellis** [comment]
solved by #1709
