### ISSUE TITLE
[bug]: 2.0.0-beta.2 - invalid value for <svg> attribute width="1.6rem"

### ISSUE THREAD

**Issue by innerdvations** [strapi/design-system#1707]
### What version of strapi-design-system are you using?

Strapi Design System Version: 2.0.0-beta.2

### What's Wrong?

When running the e2e tests, I noticed this error during the login:

Error: Invalid value for <svg> attribute height="1.6rem"

### To Reproduce

I only noticed this in e2e tests, because it seems to happen in a flash after login button is clicked before the page navigates to the logged in admin screen.

### Expected Behaviour

There should not be an error

**Comment by joshuaellis** [comment]
solved by #1708
