### ISSUE TITLE
[bug]: Checkbox missing padding in RTL

### ISSUE THREAD

**Issue by zaaakher** [strapi/design-system#1714]
### What version of strapi-design-system are you using?

npm@10.2.5

node@18.19.0

@strapi/design-system@1.18.0

### What's Wrong?

Upon creating this [PR](https://github.com/strapi/strapi/pull/20273) in Strapi admin. I realized the checkbox doesn't have a space between the box and the label when the language is RTL.

## When LTR 
![image](https://github.com/strapi/design-system/assets/46135573/b86f5abd-9942-49c4-bb9e-ed5f2ce3e1b7)

## When RTL

![image](https://github.com/strapi/design-system/assets/46135573/30a2007d-1f76-4780-b92f-1bc43022b26f)

Upon further investigation it seems to be coming from [here](https://github.com/strapi/design-system/blob/958fe5a991ad51dc80ed3ce93f2b8f8d5763e451/packages/strapi-design-system/src/Checkbox/Checkbox.tsx#L48) 

### To Reproduce

1- Create a `<div>`

2- Set the property `dir` to `RTL

3- Place a `<Checkbox/>` component inside that RTL div.

4- See the lack of space between the label and the box, switch back and forth between `rtl` and `ltr` to see the difference.

### Expected Behaviour

It should use `paddingStart` instead of `paddingLeft` so that it's consistent regardless of direction. I was gonna make a PR for it but [handleResponsiveValues.ts](https://github.com/strapi/design-system/blob/develop/packages/strapi-design-system/src/helpers/handleResponsiveValues.ts) looked too complex for me to get through it in the short time I have. So I kindly leave it to you. I appreciate your efforts :)

**Comment by madhurisandbhor** [comment]
It should work fine in V2 as its using `gap` instead of `padding`.
