### ISSUE TITLE
[bug]: Badge add transparent as possible backgroundColor value and find a way to overwrite the textColor with the prop passed

### ISSUE THREAD

**Issue by simotae14** [strapi/design-system#1724]
### What version of strapi-design-system are you using?

DS - v2.0.0-beta.3
Node - v20.10.0
NPM - v10.2.3
YARN - v4.0.1
Browser - Chrome

### What's Wrong?

it is impossible to pass transparent as backgroundColor (we have a Type issue)

And if you try to pass a value to the textColor prop it doesn't apply

### To Reproduce

Create a Badge content in the cms and try to pass the two props, transparent is not allowed as backgroundColor and the textColor doesn't work

### Expected Behaviour

I think transparent needs to be an option for the the background color and the textColor needs to be applied

**Comment by cybertron288** [comment]
Hi @simotae14 @joshuaellis,
I have raised the PR for above issue, https://github.com/strapi/design-system/pull/1740 can you please review the changes.
