### ISSUE TITLE
[Content Manager] Multiple Media field : carrousel arrow is way too tiny

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/design-system#1778]
### Required System information

Node.js version: 20.9.0
Strapi version: 5.0.0-beta.13
Operating system: Windows WSL

### Describe the bug

When you have a multiple media field, and multiple assets added, the carrousel arrow to see all your assets is tiny and almost not visible.

### Steps to reproduce the behavior

1. Create a CT with Multiple Media field
2. Go to CM
3. Create an entry for this CT
4. Add more than 1 media in the media field
5. See the tiny arrow

### Expected behavior
 Carrousel arrow should be bigger.

### Screenshots

![image](https://github.com/strapi/design-system/assets/97893822/6869f778-f92a-4ede-aa4c-14bb727a23bd)

**Comment by remidej** [comment]
Fixed in #1784, released in rc.11
