### ISSUE TITLE
[bug]: Icons are not centered in the checkboxes

### ISSUE THREAD

**Issue by lucasboilly** [strapi/design-system#1819]
### What version of design-system are you using?

Browser: Arc

### What's Wrong?

Icons are not centered in the checkboxes, it's very visible in the intermediate state.

![CleanShot 2024-11-12 at 12 21 53@2x](https://github.com/user-attachments/assets/9bdafd64-9b5b-430b-8020-cff2fc740f0f)

### To Reproduce

Find any checkbox (ex: in the edit view table).

### Expected Behaviour

Icons should be centered.

**Comment by adarshk01** [comment]
hey, could you assign me this issue

**Comment by PlanckConst** [comment]
I found the issue rooted from the parent container missing

```
justify-content: center
align-items: center
```

Path: packages\design-system\src\components\Checkbox\Checkbox.tsx

What was changed:
Inline Styling for **CheckboxIndicator**

```
<CheckboxIndicator style={{ display: 'inline-flex', pointerEvents: 'auto', justifyContent: 'center', alignItems: 'center' }} forceMount>
          {checked === true ? <CheckIcon width="1.6rem" fill="neutral0" /> : null}
          {checked === 'indeterminate' ? <Minus fill="neutral0" /> : null}
        </CheckboxIndicator>
```

![image](https://github.com/user-attachments/assets/33579739-7066-4a07-9d12-5cfd7bb30063)

Pull request: [https://github.com/strapi/design-system/pull/1821](https://github.com/strapi/design-system/pull/1821)

**Comment by lucasboilly** [comment]
Hey @PlanckConst, I answered in the PR, thanks again :)
