### ISSUE TITLE
[bug]: The link’s icon color doesn’t change on hover

### ISSUE THREAD

**Issue by lucasboilly** [strapi/design-system#1825]
### What version of design-system are you using?

Browser: Arc

### What's Wrong?

The link’s icon color doesn’t change on hover.

https://github.com/user-attachments/assets/1804ff57-e5f7-48cf-9f70-5ef2aafdbe3b

### To Reproduce

You can see it on any back button, for example when opening an entry.

### Expected Behaviour

The color of the icon should match the color of the text when hovered (`Primary500`).

**Comment by yas8say** [comment]
Hi there, how can i get started ?
