### ISSUE TITLE
add input json component

### ISSUE THREAD

**Issue by ComfortablyCoding** [strapi/design-system#498]
It was suggested by Hicham on the discord to create an issue for this so it can be discussed with the team. 

The current [InputJSON component](https://github.com/strapi/strapi/tree/master/packages/core/admin/admin/src/content-manager/components/InputJSON) used in the content manager is not currently available via the design system.

This component should be added as it is quite useful for plugin developers for json inputs such as a field for the user to input request body data (my use case). The alternative at the moment is to either use a textarea or the developer creates their own version of it, neither of which are desirable alternative.

**Comment by jcAtRsi** [comment]
+1 for this.

**Comment by joshuaellis** [comment]
I'll bring this up in the next community review meeting.

**Comment by gu-stav** [comment]
@joshuaellis I think this is more for the design-system sync meeting :)

**Comment by ComfortablyCoding** [comment]
Thank you!
