### ISSUE TITLE
Longer titles pushing Publish and Save buttons off screen

### ISSUE THREAD

**Issue by ymclapp** [strapi/design-system#530]
When in Content Manager and I try to Publish an item that is in Draft, I can get into the item, but there is no Publish or Save buttons.  I found that it is being caused by the item in the h1 at the top of the div for the header that shares the space of those two buttons is too long and there is not a scroll bar to get to them.  I went into inspector and deleted the h1, the Publish and Save showed up, I hit the Publish, and it worked.

Here is a link to the discord where I put a screenshot of the missing buttons and the too long header:  https://discordapp.com/channels/811989166782021633/841755530007805983/943509621631516742

**Comment by HichamELBSI** [comment]
Hi @ymclapp, can you please format your message properly.

**Comment by ymclapp** [comment]
> Hi @ymclapp, can you please format your message properly.

Hi!  Sorry about that. Is it correctly formatted now?

**Comment by HichamELBSI** [comment]
Thanks 😊

**Comment by HichamELBSI** [comment]
Maybe we can set a `maxWdith` to the title header WDYT @maevalienard?

**Comment by HichamELBSI** [comment]
It solves the problem of accessing the buttons but on the other hand, we have to truncate the title text. FYI this bug happens only when the title is a single long word (e.g. A url).

![Screenshot 2022-02-17 at 10 57 35](https://user-images.githubusercontent.com/7756284/154451648-f38d7a2e-34c1-4628-b85e-ae047a8a523c.png)
![Screenshot 2022-02-17 at 10 58 17](https://user-images.githubusercontent.com/7756284/154451652-eca5c9c6-8c64-48f0-b1eb-2decb24be749.png)

**Comment by maevalienard** [comment]
@HichamELBSI  In my opinion, it's okay to truncate the title if it's one single long word. The title is based on an input below so it's easily accessible I guess :)

**Comment by HichamELBSI** [comment]
If we choose to truncate, it will be truncated for all the use cases. Single long word or not.

**Comment by maevalienard** [comment]
I see. The thing is not really friendly to have an overflowing title either. I'd go for the truncation and see how it goes :)

**Comment by joshuaellis** [comment]
I believe this was closed by #905
