### ISSUE TITLE
Control keys are hijacked within `Table` component

### ISSUE THREAD

**Issue by dzcpy** [strapi/design-system#541]
There is a weird bug that `Table` component actually hijacks keys like `left`, `right`, `home`, `end` etc. for elements within it.
Example code:
```jsx
() => {
  const [content, setContent] = useState('Try using control keys');
  return <Table>
    <Box padding={10}>
        <Textarea placeholder="This is a content placeholder" label="Content" name="content" hint="Description line" error={content.length < 5 ? 'Content is too short' : undefined} onChange={e => setContent(e.target.value)}>
      {content}
    </Textarea>
  </Box>
</Table>;
}
```
Try editing it using arrow keys and home / end keys, they don't work.

**Comment by dzcpy** [comment]
Quck workaround:
Add a `onKeyDown={e => e.stopPropagation()}` to solve this issue. However I hope `strapi` can fix it

**Comment by HichamELBSI** [comment]
Hello @dzcpy, remove the key handlers is not planned since it is used to allow the keyboard navigation in the table.
