### ISSUE TITLE
Disabled Switch doesn't show if the value is on or off

### ISSUE THREAD

**Issue by dzcpy** [strapi/design-system#584]
![image](https://user-images.githubusercontent.com/203980/159191457-0185c165-a512-4ca3-9377-af1ed83816f3.png)
As shown in the image above, on the left side it's the disabled Switch, but actually it has a default value although it can't be changed. But since the change of the design, there's no way I can tell if it's on or off. It's quite inconvinient. Please make it visually distinguishable. Thanks!

**Comment by gu-stav** [comment]
Thank you for opening the issue. I forgot about this case during the refactoring and opened another PR to fix the issue: https://github.com/strapi/design-system/pull/585 Does that work for you?
