### ISSUE TITLE
Add calendar view

### ISSUE THREAD

**Issue by WardenCommander** [strapi/design-system#601]
This two calendar options would be great:
month view:
https://github.com/wojtekmaj/react-calendar
year view:
https://github.com/BelkaLab/react-yearly-calendar

**Comment by HichamELBSI** [comment]
Hello @WardenCommander, this component isn't planned to be re-work for the moment but your comment will be taken into account if it should be changed.

**Comment by WardenCommander** [comment]
Hello @HichamELBSI I was proposing new component not reworking existing one, as some of this views would help some people, me included
