### ISSUE TITLE
Radio button is not checked when selected value is passed on first load

### ISSUE THREAD

**Issue by PritamSangani** [strapi/design-system#607]
### Required System information

- Npm version: 8.1.2
- NodeJS version: 14.15.1
- Strapi Design System version: 1.1.0
- Browser: Firefox 

### Describe the bug

When a selected value is passed to a radio group on page load, the selected radio button is not checked.

### Steps to reproduce the behavior

https://codesandbox.io/s/divine-resonance-pjrzj3?file=/src/App.js - this code sandbox demonstrates the issue. 
I have passed a default value to the selected useState. However, the radio button which matches the selected value is not checked when the page first loads.

### Expected behavior

The radio button which matches the selected value should be checked.

### Code snippets

I believe this can be fixed by passing a `checked` prop to `RadioInput` component in `BaseRadio` (https://github.com/strapi/design-system/blob/main/packages/strapi-design-system/src/BaseRadio/BaseRadio.js)

**Comment by PritamSangani** [comment]
I can create a PR to fix the issue and add appropriate tests if you think this is an appropriate fix.

**Comment by HichamELBSI** [comment]
Hi @PritamSangani, thanks for your feedback. Of course, feel free to open a PR 👍🏽
