### ISSUE TITLE
KeyboardNavigable component always calls `preventDefault()` on arrow key events

### ISSUE THREAD

**Issue by jcberquist** [strapi/design-system#614]
### Required System information

- Npm version 8.7.0
- NodeJS version: 16.14.2
- Strapi Design System version: 1.1.0
- Browser: Brave 1.39.111

### Describe the bug

`KeyboardNavigable` component always calls `preventDefault()` on arrow key events. I think this is unintended since `preventDefault()` gets called again if the `isValidFocusedElement()` check passes.

### Steps to reproduce the behavior

Please see the discussion here https://github.com/strapi/strapi/issues/13342 for an instance of the issue. If a form input field is contained in a `KeyboardNavigable` component, then the arrow keys will not work to move the cursor in that field. As the original issue there has it, using the latest Strapi version:

1. Content-Type builder: Create a singular type and add a repeatable component with a text input
2. Content Manager: Add a component, type anything in the input field and try to move the cursor with the arrow keys.

### Expected behavior

`KeyboardNavigable` component calls `preventDefault()` only when the `isValidFocusedElement()` check passes.

**Comment by yanniskadiri** [comment]
Closing this one and relating it to #642 as we need to fix arrow key handling in both cases.
