### ISSUE TITLE
Flex does not show a gap whatever I do.

### ISSUE THREAD

**Issue by Martin-Eckleben** [strapi/design-system#621]
### Required System information

- Npm version: 8.11.0
- NodeJS version: 16.15.1
- Strapi Design System version: https://registry.npmjs.org/@strapi/design-system/-/design-system-0.0.1-alpha.79.tgz
- Browser: Chrome Version 102.0.5005.115 (official build) (64-Bit)

### Describe the bug

Can´t get the Flex Component to display a gap.

https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-technical-components-flex--base
says:
"gap
Supports responsive values
{ desktop: number, mobile: number, tablet: number } | number | number[] | string"
but does not give examples.

`<Flex direction="column" gap={10}>`
`<Flex direction="column" gap="10">`
`<Flex direction="column" gap="10px">`
`<Flex direction="column" gap={"10"}>`
`<Flex direction="column" gap={"10px"}>`
`<Flex direction="column" gap={{desktop:10}}>`
etc.

all don´t show a gap.

### Steps to reproduce the behavior

```
<Flex direction="column" gap={10}>
      <div>test1</div>
      <div>test2</div>
      <div>test3</div>
      <div>test4</div>
      <div>test5</div>
</Flex>
```

### Additional context

I´m developing a plugin for "@strapi/strapi": "4.1.8"

Thank you all for your work!

**Comment by HichamELBSI** [comment]
Hi @Martin-Eckleben,

The Design System version depends (unfortunately) on the Strapi version for the moment. The `gap` property of the `Flex` component has been added in `Strapi Design System v1.1.0` which is available on `Strapi v4.1.9`. If you update your Strapi version to the `4.1.9`, you'll be able to use it.

**Comment by Martin-Eckleben** [comment]
Thank you very much for your time and help!

It would have been almost impossible for me to know.

Maybe the design-system documentation should be versioned like Laravel´s i.e.?
https://laravel.com/docs/5.8
https://laravel.com/docs/5.7

**Comment by HichamELBSI** [comment]
It is actually, https://github.com/strapi/design-system/releases 😉 

But I personally think that it is easy to be lost as a user because you have to know that the version of the Design System depends on the Strapi version and then you have to check the version that is used for your Strapi version and then check the Design System release notes 😅.
