### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by btd1337** [strapi/design-system#632]
### Required System information

- Npm version: 8.5.4
- NodeJS version: v16.14.2
- Strapi Design System version: 4.3.2-beta1
- Browser: All

### Describe the bug

This project has peer-dependencies errors

### Steps to reproduce the behavior

```
npm install --strict-peer-deps
```

### Expected behavior

Install dependencies successfully

### Current behavior

```
 ERR_NPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ @strapi/strapi
  └─┬ @strapi/admin
    ├─┬ @strapi/design-system
    │ └── ✕ unmet peer @strapi/icons@^0.0.1-alpha.73: found 1.1.1 in @strapi/admin
    └─┬ react-virtualized
      ├── ✕ unmet peer react@"^15.3.0 || ^16.0.0-alpha": found 17.0.2 in @strapi/admin
      └── ✕ unmet peer react-dom@"^15.3.0 || ^16.0.0-alpha": found 17.0.2 in @strapi/admin
```

### Additional context

The error occurs also with [pnpm](http://pnpm.io/)

**Comment by gu-stav** [comment]
I believe this issue should be fixed in the latest release by https://github.com/strapi/design-system/pull/620 . In case you are still running into problems feel free to ping me :)
