### ISSUE TITLE
Typescript Support or DefinitelyTyped

### ISSUE THREAD

**Issue by nextrapi** [strapi/design-system#633]
Hi there!

I was wondering if there are any plans for typescript support, or whether I should write type declarations and submit them to DefinitelyTyped. Which if I am not mistaken, is simply a matter of converting the propTypes and defaultTypes to typed functions and interfaces. 

Please guide me to the correct way of contributing regarding this.

**Comment by joshuaellis** [comment]
Closing in favour of our tracking issue #983
