### ISSUE TITLE
SimpleMenu children proptype is too restrictive.

### ISSUE THREAD

**Issue by HichamELBSI** [strapi/design-system#665]
Required System information
Npm version: 8.5.0
NodeJS version: 16.4.2
Strapi Design System version: 1.2.0
Browser: Chrome
Describe the bug

While customizing a MenuItem components for our needs with SC, I figured that an error on SimpleMenu children proptype is trigger. IMO, the proptype should accept a react node instead of a strict type of component.

**Steps to reproduce the behavior**
- Use the SimpleMenu
- Customize a MenuItem with styled-component
```jsx
const StyledMenuItem = styled(MenuItem)`
   ...
`;
```
- The SimpleMenu children proptype should trigger an error

**Comment by HichamELBSI** [comment]
What do you think of having a react node children instead of the current strict ⬇️ 
```js
const menuItemType = PropTypes.shape({ type: PropTypes.oneOf([MenuItem]) });
...
children: PropTypes.oneOfType([PropTypes.arrayOf(menuItemType), menuItemType]).isRequired,
```

**Comment by gu-stav** [comment]
@HichamELBSI We are running into the same problem [here](https://github.com/strapi/design-system/pull/662) and also had to relax the prop-types. There I'd say: I'm good with it :)

**Comment by gu-stav** [comment]
Fixed in https://github.com/strapi/design-system/pull/662
