### ISSUE TITLE
[RFC] Accordion V2 API design

### ISSUE THREAD

**Issue by joshuaellis** [strapi/design-system#694]
👋🏼 **Disclaimer** I may be missing relevant context

## A clear and concise description of what the feature is

I think the accordion API design could be _refined_, that is, I find it confusing that I **need** to control the state of the `Accordion`, whilst I think having a way for the user to do so is important, by default IMO it makes more sense to control this for them, this is especially true with the `AccordionGroup` which I would expect the `Accordion` to normally close it's sibling automatically (which is technically possible since I have to control the state of the component). Bringing the state by default into the component would make it easier for people to use & create a more powerful group.

Secondly, should we be passing `className` so people can extend the styles?

## Why should this feature be included?

Because I believe it will make it easier for people to use the component in their projects by removing unnecessary overhead of state/ids etc. 

## Please provide an example for how this would work

I think `radix-ui` is a great example of a simple component API. I think more investigation however, into how accordions are used in the application would be beneficial to ensure things we change aren't required (although being able to manually control the state of the component will **not** be removed). This also may not actually require a V2, it may be possible to refactor the V1 components...

**Comment by HichamELBSI** [comment]
Hi @joshuaellis,

I personally don't have a strong opinion about the state. I am not sure but I think that some special cases may prevent this change on Strapi especially on the content manager which can display the accordion in different states. Depending on the permissions of the Admin user, the component or part of the component can be hidden or replaced, disabled the component or part of the component in read only mode, etc. I don't have all the use cases in mind but it's something that should be really well tested before updating the component API. 

Except this doubt, I don't really have an opinion against this update. I also think that the controlled state of the accordions would facilitate the use of this component.

About the style customisation, the DS is provided with guidelines. These guidelines allow developers to follow the Strapi UI, keep the consistency of the Strapi brand in its applications (Strapi and its plugins, Strapi Cloud). We therefore avoid providing customization APIs for the UI when it is not planned or used by us (for the moment). That being said, customization is always possible by creating and overwrite the component's style with styled-components but that is something we should avoid as much as possible to keep consistency.
