### ISSUE TITLE
Number Input not working correctly

### ISSUE THREAD

**Issue by lolafkok** [strapi/design-system#696]
### Required System information
Node.js version: v14.19.1
Strapi version: 4.3.4
Database: MySQL
### Describe the bug

Spin up a Strapi and create a Number Field with Type Decimal or go to the Number Input in Design System Storybook (https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-numberinput--base).
Enter for example **0.5** and leave the field with `Tab`. 
**Output:** 5 instead of 0.5.
If you enter **3.5** the output is **35** and so on. 
If you enter **0,5** the number is changed to **0.5** but when you leave the field it switches back to **0,5**.

In v3 this field was able to display dot separated values, you could define a default of for example **0.5** and the user was able to enter dot separated values.
Now this is just unusable.

Also: If you use the arrow up and down keys you can sometimes (couldn't reproduce in Design System Storybook atm) get completely rubbish numbers **like 0,5999999**. 

Feeling like a beta-tester in v4 after shipping production-ready applications with v3, somehow.

**Comment by gu-stav** [comment]
Hello @lolafkok and @iceteabob, I've tried to reproduce the issue here: https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-components-numberinput--base , but it works on my side. Can you confirm that?

**Comment by ronronscelestes** [comment]
Just a note:
I am able to reproduce this behavior but I don't think it is a bug (at least on my machine) - the component is using `getDefaultLocale()` to format the number, in France if you want a decimal the syntax is `0,5` not `0.5`
Would you be able to log `getDefaultLocale()` locally to ensure it's not a locale context causing this formatting?

**Comment by INNOVATIVEGAMER** [comment]
Yes @ronronscelestes. You are right. I have looked into this issue and found that its related to locale context and not code issue.
I am attaching the screenshots for reference =>
1. My local timezone/location (Working as expected) | India -
![Screenshot 2022-10-04 010216](https://user-images.githubusercontent.com/55017197/193663102-f8510a64-1769-4ce6-9e24-c07dea542fac.png)

2. Paris timezone/location (Working as expected) | France -
As you stated in France if you want a decimal the syntax is 0,5 not 0.5

With point/dot/decimal -
![Screenshot (32)](https://user-images.githubusercontent.com/55017197/193664759-0b25879b-e683-4f51-bf92-7a527ecdae50.png)

With comma -
![Screenshot 2022-10-04 010031](https://user-images.githubusercontent.com/55017197/193663100-ce75f095-9a9e-450e-acce-1a26f207f49f.png)

@joshuaellis I think we can close this issue.
