### ISSUE TITLE
Implement text-align on Typography

### ISSUE THREAD

**Issue by gu-stav** [strapi/design-system#718]
## Bug report

In https://github.com/strapi/strapi/pull/14536/files#diff-f127d9b182eb05d96ddf5f8ea2e60c8c071c13d46e468490a47f4a6fbdd0171d and a few other places already it became evident that it would be beneficial to have `text-align` implemented as `textAlign` or `align` property on the `Typography` component.

### Required System information

- Npm version: Not applicable
- NodeJS version: Not applicable
- Strapi Design System version: 1.2.5
- Browser:: Not applicable

**Comment by joshuaellis** [comment]
IMO `textAlign` is clearer, `align` _could_ imply a `flex` property for examples 👍🏼
