### ISSUE TITLE
Enable peer dependencies on React 18.x

### ISSUE THREAD

**Issue by Nick-Gabe** [strapi/design-system#723]
I'm currently having peer dependencies errors when using React 18.x

**Comment by Nick-Gabe** [comment]
Oh, I Inderstand, I faced this issue some days ago when I updated React and a library stopped working 😅
So yes, it needs to be further tested, thank you for the reply!

**Comment by joshuaellis** [comment]
This was done in `1.7.2` I should have linked the PR then!
