### ISSUE TITLE
Strapi icon out-of-date

### ISSUE THREAD

**Issue by gu-stav** [strapi/design-system#725]
## Bug report

The Strapi logo in the icons package is out-of-date and needs to be replaced with the new one: https://github.com/strapi/design-system/blob/main/packages/strapi-icons/assets/icons/Strapi.svg

### Required System information

- Npm version: Not applicable
- NodeJS version: Not applicable
- Strapi Design System version: 1.2.5
- Browser: Not applicable

### Expected behavior

The logo was recently updated and needs an update in the DS too.

### Screenshots

The icon is displayed on the Strapi dashboard:

<img width="410" alt="Screenshot 2022-10-19 at 15 00 45" src="https://user-images.githubusercontent.com/2244375/196697908-69c9450a-e1bc-42e9-84df-98a646625060.png">

**Comment by gu-stav** [comment]
@maevalienard Do we have an SVG somewhere that we can use?

**Comment by maevalienard** [comment]
@gu-stav Sure! 🚀 Here it is:
![StrapiMonogram](https://user-images.githubusercontent.com/54801383/196712016-c47b771a-bb79-479b-aa65-cf926a6367c5.svg)
