### ISSUE TITLE
Required prop not working on TextInput component

### ISSUE THREAD

**Issue by leonardo-adorno** [strapi/design-system#760]
### Describe the bug

Hello, i'm trying to use the prop required on TextInput, like the example below:

        <TextInput
          placeholder="FY23_"
          label="Identification"
          name="text"
          hint="Max 40 characters"
          error={getErrorName()}
          required={true}
          onChange={(e) => setName(e.target.value)}
          value={name}
        />

But it's not working well. The label is receiving the required prop, but the input field is not receiving.

![image](https://user-images.githubusercontent.com/50339842/200625392-46585623-6e98-466b-a01d-c0d14b024e90.png)

This seems like a bug.

**Comment by ronronscelestes** [comment]
hi @leonardo-adorno thank you for highlighting this issue, it is indeed a bug!
