### ISSUE TITLE
[bug]: Icons for blog and careers page in Admin Dashboard 

### ISSUE THREAD

**Issue by malgamves** [strapi/design-system#793]
### What version of strapi-design-system are you using?

- Npm version: 8.11.0
- Node version: 16.16.0
- Design System: 1.3.3
- Browser: Firefox and Chrome

### What's Wrong?

The icons in for the strapi dashboard for the blog and careers page seem to be broken. 
<img width="385" alt="image (6)" src="https://user-images.githubusercontent.com/25641936/204347715-7921fa1f-3803-43bb-8a8e-ff32770f9c0e.png">
<img width="234" alt="image (5)" src="https://user-images.githubusercontent.com/25641936/204347727-0924b43c-26d7-479d-9359-eea2a4f0f8b2.png">

### To Reproduce

Create a brand new Strapi application, run your Strapi server and open the admin panel. after logging in and navigating to your dashboard, you should see the issue. 

### Expected Behaviour

The icons should match those of the Strapi [brand guide](https://handbook.strapi.io/strapi-brand-book-2022).

**Comment by simotae14** [comment]
Hey @malgamves I saw the issue and also a possible solution in the Strapi Repo
