### ISSUE TITLE
[bug]: Connection between label + input is broken on DateTimePicker and TimePicker

### ISSUE THREAD

**Issue by gu-stav** [strapi/design-system#800]
### What version of strapi-design-system are you using?

- DS Version: 1.4.0

### What's Wrong?

When clicking on the label of the `TimePicker` or `DateTimePicker` component, the focus is not properly set.

### Timepicker

1. Open https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-timepicker--base
2. Click on the label

### DateTimePicker

1. Open https://design-system-git-main-strapijs.vercel.app/?path=/story/design-system-components-datetimepicker--base
2. Click on the label

### Expected Behaviour

- Timepicker: I expect the field to be focused
- DateTimePicker: I expect the date-field tp be focused

**Comment by joshuaellis** [comment]
This should be resolved as part of #911
