### ISSUE TITLE
[bug]: Combobox sends you to bottom of page

### ISSUE THREAD

**Issue by Boegie19** [strapi/design-system#818]
### What version of strapi-design-system are you using?

- Node version: v18.9.1
- Npm version: 8.19.2
- Strapi design version: 1.4.1
- Browser Google Chrome

### What's Wrong?

when I open a Combobox it sends me to the bottom of the page 
![Alt Text](https://i.gyazo.com/363ea37292dbbf885da239e43f15dbfd.gif)

### To Reproduce

Add Combobox
Add ComboboxOptions
make the body height 200% 
open the Combobox
get send to the bottom of your screen

### Expected Behaviour

It should stay near the Combobox  so that I don't have to scroll back to the top of the page

**Comment by deanmchugh** [comment]
Im getting the same behaviour. Has anyone found a solution yet?

**Comment by joshuaellis** [comment]
If either of you can provide a codesandbox demonstrating the issue that'd be really helpful to get the ball rolling 😄

**Comment by Boegie19** [comment]
https://codesandbox.io/s/strapi-combobox-end-of-page-example-u6llvn
the it is caused by the css 
```css
#root {
  height: 200vh;
}
```
if I remote the root height it fixes itself if eve if the root height is only 100% it still goose down a little bit

**Comment by Boegie19** [comment]
@joshuaellis Anything else you need?

**Comment by joshuaellis** [comment]
> @joshuaellis Anything else you need?

No I haven't had the time to look yet and neither has another dev. I'll let you know when I have an update.
