### ISSUE TITLE
[bug]: minDate not working for DatePicker component

### ISSUE THREAD

**Issue by Zharkan** [strapi/design-system#822]
### What version of strapi-design-system are you using?

- NPM : 9.2.0
- Node : 16.19.0
- SDS version : 1.4.1
- Browser tested : firefox-developer-edition

### What's Wrong?

minDate prop is not working at all and is ignored.

### To Reproduce

```jsx
<DatePicker
        label={"Select a 
        minDate={new Date(2022, 12, 22)}
      />
```

### Expected Behaviour

Expecting minDate to actually limit the min date.

**Comment by simotae14** [comment]
Thanks @Zharkan we saw the issue and the fix will be available soon. Thanks again
