### ISSUE TITLE
[chore]: Integrate the `website` in the monorepo

### ISSUE THREAD

**Issue by joshuaellis** [strapi/design-system#855]
### A clear and concise description of what the feature is

The website should be part of the monorepo and consume the DS

### Why should this feature be included?

Because it adds another touch point of visibility in how our package behaves with other libraries & scenarios.

### Please provide an example for how this would work

`lerna.json`

```json
{
  "packages": ["packages/*", "website"],
  "version": "1.5.0",
  "npmClient": "yarn"
}
```

**Comment by teezBlaze** [comment]
So the solution to this is, copy the above code and paste it in the lerna.json file here https://github.com/strapi/starters-and-templates/blob/main/lerna.json ? 

I am a beginner in Opensource contributing, so don't know if this is what the solution is. Any help is appreciated. Thank you!

**Comment by INNOVATIVEGAMER** [comment]
@teezBlaze Ya, that's the work here. 

So mainly tasks will be as follows ->
1. Change the lerna configuration and package.json configuration to contain `website` folder
2. Bootstrap the project using lerna to check everything is working fine

@joshuaellis WDYT ? Is this the whole process ?

**Comment by joshuaellis** [comment]
> Bootstrap the project using lerna to check everything is working fine

This is the crucial bit, iirc last time i had issues with `styled-components` so there might be some friction there. But yeah, that's pretty much it :)

**Comment by teezBlaze** [comment]
Thank you @INNOVATIVEGAMER and @joshuaellis for your replies. 

So here's what I have done so far:

1. Configured lerna.json and package.json.
2. Copied the `website` folder from `design-system` and pasted it into the fork of `starters-and-templates`.

Can somebody verify if I am on the right path? See the screenshots for more clarity.
![1](https://user-images.githubusercontent.com/131569178/235077621-2810f936-5c26-4727-8069-9cd0a18ba2e7.png)
![2](https://user-images.githubusercontent.com/131569178/235077651-a5ba59d2-bdfb-4762-b7f4-87f56f530438.png)

**Comment by teezBlaze** [comment]
> @teezBlaze Ya, that's the work here.
> 
> So mainly tasks will be as follows ->
> 
> 1. Change the lerna configuration and package.json configuration to contain `website` folder
> 2. Bootstrap the project using lerna to check everything is working fine
> 
> @joshuaellis WDYT ? Is this the whole process ?

About the 2nd point, I tried executing `lerna bootstrap` and I get the below results. Can you verify if this is the way?
![3](https://user-images.githubusercontent.com/131569178/235079202-dae484d5-0dd0-4ce7-aac6-e9d42a48761c.JPG)

**Comment by INNOVATIVEGAMER** [comment]
@teezBlaze I think you need some info over what are monorepos and what lerna is actually doing here.
Monorepo - https://youtu.be/9iU_IE6vnJ8
Lerna - https://youtu.be/YtnChOgCwjY
These are just glimpse of these concepts but I think understanding these two videos will clear your doubts. Especially second video for this PR.

**Comment by teezBlaze** [comment]
Thank you @INNOVATIVEGAMER for the resources. I will look more into this and come back to this issue.

**Comment by teezBlaze** [comment]
> > starters-and-templates
> 
> I'm not sure why you're trying to put it in there, we just want the website to part of the monorepo in this repository :)

Okay, will do accordingly. I just have to go through monorepos and lerna, and will come back to solve the issue.

**Comment by joshuaellis** [comment]
won't be doing, we're going all in on storybook.
