### ISSUE TITLE
[bug]: Typescript: "Cannot find module @strapi/design-system/Button'" after v1.2.8

### ISSUE THREAD

**Issue by mpuxted** [strapi/design-system#873]
### What version of strapi-design-system are you using?

- Npm version: 8.11.0
- Node version: 16.16.0
- Strapi design system version: 1.3.1

### What's Wrong?

Design system components cannot be used in typescript plugins after v1.2.8 of design-system

I have a typescript implementation of strapi, and I've created a plugin using typescript within it. Inside the plugin I am creating components that use design-system components, such as @strapi/design-system/Button

Using v1.2.8 of design system, I have no issues.
Using v1.3.0 (or above) I have the following error: 

![image](https://user-images.githubusercontent.com/54951494/215801247-481dd64c-a5cb-48f9-b0ea-38413fff86f5.png)

`Cannot find module '@strapi/design-system/Button' or its corresponding type declarations.`

This error causes the build to fail. Adding `@ts-ignore` allows the build to complete and the components display without an issue

### To Reproduce

1. Create a typescript strapi project
2. Use the CLI to create a typescript plugin (`npm run strapi generate`)
3. Try to use a design system component in a plugin component 
e.g `import { Button } from "@strapi/design-system/Button";`
4. IDE or `npm run build` produces error:
`Cannot find module '@strapi/design-system/Button' or its corresponding type declarations.`

(5. add.  `@ts-ignore` and the build is successful)

### Expected Behaviour

1. Create a typescript strapi project
2. Use the CLI to create a typescript plugin (`npm run strapi generate`)
3. Try to use a design system component in a plugin component 
e.g `import { Button } from "@strapi/design-system/Button";`
4. Project is able to build

**Comment by joshuaellis** [comment]
Firstly, we don't export any ts types at the moment so that's a hinderance.

Secondly, I wouldn't do a direct import, instead do this – `import { Button } from '@strapi/design-system'`

We're working on TS types which we believe will help this, but stopping direct imports would be more helpful because TS doesn't support `exports` in the package.json (yet)

**Comment by mpuxted** [comment]
![you-got-me-there-you-got-me](https://user-images.githubusercontent.com/54951494/215807116-e37af94b-f271-4bfa-97a5-2abeb7a2fe8f.gif)

**Comment by mpuxted** [comment]
Although @joshuaellis you may want to consider updating this article: https://strapi.io/blog/how-to-build-a-plugin-with-typescript#:~:text=import%20%7B%20Button%20%7D%20from%20%27%40strapi/design%2Dsystem/Button%27%3B
