### ISSUE TITLE
How do I make TextInput flex-grow?

### ISSUE THREAD

**Issue by Martin-Eckleben** [strapi/design-system#914]
### Context

How do I make Strapi design-systems TextInput flex-grow?
`style={{ flexGrow: 1 }}` does not work.
`flexGrow="1"` does not work as well.

EDIT:
I seem to be able to do it by wrapping it with a flex-grow:1 div

### Proposal

TextInput should at best be able to take all classic CSS style attributes?
`style={{ flexGrow: 1 }}`

### Reasons

Obvious.

**Comment by INNOVATIVEGAMER** [comment]
> I seem to be able to do it by wrapping it with a flex-grow:1 div

I think its just the way ahead. Just wrap it around the `div` and if you want it more the DS way, you can just use `Box` instead of `div`
