### ISSUE TITLE
[bug]: Table not rendering

### ISSUE THREAD

**Issue by WardenCommander** [strapi/design-system#924]
### What version of strapi-design-system are you using?

npm: 8.19
nodejs: 18
strapi - design-system: 1.6.5
browser: Chrome

### What's Wrong?

after updating to the latest strapi and design-system version my table breaks, ima rendering year view calendar, i just copied following code and replace with strapi table components, everything was working in before last update
https://github.com/BelkaLab/react-yearly-calendar

![Screenshot 2023-03-16 112507](https://user-images.githubusercontent.com/46477089/225573294-182a5a0f-51d0-4da1-9696-48a45aa674b1.png)

### To Reproduce

build a table

### Expected Behaviour

render a table

**Comment by WardenCommander** [comment]
Im saying that table components { Table, Thead, Tbody, Tr, Th } are not working for a table that I'm using in strapi backend.
I used code from `react-yearly-calendar` and replace native { table, thead, tbody, tr, th } with `strapi-design-system` components { Table, Thead, Tbody, Tr, Th } and everything was working till the last update, and now I get an error like in first post.

for now, i replaced `strapi-design-system`  components { Table, Thead, Tbody, Tr, Th } back to native { table, thead, tbody, tr, th } and it's working again, so it seems there is some problem with `strapi-design-system`

**Comment by joshuaellis** [comment]
> for now, i replaced `strapi-design-system` components { Table, Thead, Tbody, Tr, Th } back to native { table, thead, tbody, tr, th } and it's working again, so it seems there is some problem with `strapi-design-system` components { Table, Thead, Tbody, Tr, Th }

Right I see, this hasn't broken any of the tables we use in the CMS, so i'd need to you to supply a reproduction of your issue please, here's a sandbox template to get you started – https://codesandbox.io/s/focused-gates-0bgt3l?file=/src/App.js

**Comment by WardenCommander** [comment]
> > for now, i replaced `strapi-design-system` components { Table, Thead, Tbody, Tr, Th } back to native { table, thead, tbody, tr, th } and it's working again, so it seems there is some problem with `strapi-design-system` components { Table, Thead, Tbody, Tr, Th }
> 
> Right I see, this hasn't broken any of the tables we use in the CMS, so i'd need to you to supply a reproduction of your issue please, here's a sandbox template to get you started – https://codesandbox.io/s/focused-gates-0bgt3l?file=/src/App.js

I copied code here:
https://codesandbox.io/s/tender-roman-z1chip

**Comment by joshuaellis** [comment]
Ah i see what's happening. We clone the children and pass them props (to give them their row number and column number) but you're not passing these props down, so for example:

```jsx
const Calendar = () => {
	return (
		<Table>
			<Tbody>
				<Tr>
					<Day />
					<DayWithProps />
				</Tr>
			</Tbody>
		</Table>
	)
}

// This will fail
const Day = () => {
	return <Td />
}

// This will work
const DayWithProps = props => {
	return <Td {...props} />
}
```

This doesn't just go for `Td` iirc it applies to most of the component at the moment – Tr / Th

**Comment by WardenCommander** [comment]
@joshuaellis ok, what should I do? or does DS need to change something?

**Comment by joshuaellis** [comment]
you should pass all your props like I showed you in the example, otherwise your component is not accessible because no cell knows where they are etc. so anything that renders those components listed above should spread the rest of props that way it'll include the parent's passed props fixing the issue you're having.
