### ISSUE TITLE
[bug]: TimePicker getClosestValue function fails into an infinite loop

### ISSUE THREAD

**Issue by ArtemGrachov** [strapi/design-system#928]
### What version of strapi-design-system are you using?

- Yarn version: 3.4.1
- NodeJS version: 16.7.0
- Strapi Design System version: 1.6.1
- Browser: Google Chrome Version 111.0.5563.64 (Official Build) (64-bit) (Linux)

### What's Wrong?

[TimePicker](https://github.com/strapi/design-system/blob/main/packages/strapi-design-system/src/TimePicker/TimePicker.tsx)'s [`getClosestValue`](https://github.com/strapi/design-system/blob/main/packages/strapi-design-system/src/TimePicker/TimePicker.tsx#L61) function fails into an infinite loop with certain date / time values. Processor consumption grows to 100%, memory consumption is actively growing, and at some point the page with the TimePicker stops to respond.

### To Reproduce

For me it reproduced with value `2023-02-17T10:25:48.328Z`. Easily "fixed" by re-selecting the time picker value.
For other dates seems to work ok.

On my project appeared a bug, that for unknown reason the Strapi page stops to respond. After some researches and observations, I have found that problem disappears after re-selecting Timepicker value.

I dug the source code a bit and added a console log into [`getClosesValue`](https://github.com/strapi/design-system/blob/main/packages/strapi-design-system/src/TimePicker/TimePicker.tsx#L61) function. The log fired infintely.

![image](https://user-images.githubusercontent.com/22654837/226377886-6e3606cc-c35e-4cb7-862c-5ac72894fe05.png)

### Expected Behaviour

TimePicker should not fail into an infinite loop.

**Comment by joshuaellis** [comment]
This was solved in 1.6.6 I believe.
